# Generated by Django 4.2.7 on 2026-03-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='section',
            field=models.CharField(choices=[('greeters', 'Greeters'), ('followup', 'Follow-Up / First Timers'), ('all', 'All Sections')], default='followup', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('section_admin', 'Section Admin'), ('staff', 'Staff')], default='staff', max_length=20),
        ),
    ]
