# Generated by Django 4.2.7 on 2026-03-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='joining_church',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('considering', 'Still Considering')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='preferred_visit_time',
            field=models.CharField(blank=True, choices=[('weekday_morning', 'Weekday Morning'), ('weekday_afternoon', 'Weekday Afternoon'), ('weekday_evening', 'Weekday Evening'), ('saturday_morning', 'Saturday Morning'), ('saturday_afternoon', 'Saturday Afternoon'), ('sunday_after_service', 'Sunday After Service')], max_length=30, null=True),
        ),
    ]
