# Generated by Django 4.2.7 on 2026-03-18 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiries', '0002_alter_member_joining_church_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='greeter_assigned_to',
            field=models.ForeignKey(blank=True, help_text='Greeter staff member assigned to welcome this visitor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='greeter_assigned_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='member',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Staff member responsible for follow-up / visitation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email & SMS')], max_length=20),
        ),
    ]
