# Generated by Django 4.2.7 on 2026-03-29 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiries', '0003_member_greeter_assigned_to_alter_member_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('new', 'New Visitor'), ('returning', 'Returning Visitor'), ('regular', 'Regular Attendee'), ('member', 'Full Member'), ('integrated', 'Integrated Member'), ('inactive', 'Inactive')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integrated_on', models.DateField(default=django.utils.timezone.now)),
                ('pathway', models.CharField(choices=[('membership_class', 'Membership Class'), ('water_baptism', 'Water Baptism'), ('cell_group', 'Cell Group'), ('ministry', 'Ministry Involvement'), ('other', 'Other')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integrated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='integrations_handled', to=settings.AUTH_USER_MODEL)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration', to='enquiries.member')),
            ],
        ),
    ]
