# Generated by Django 4.2.7 on 2026-03-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_alter_member_status_integration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='pathway',
            field=models.CharField(choices=[('Fully Integrated', 'Fully Integrated')], max_length=30),
        ),
    ]
