# Generated by Django 4.2.7 on 2026-03-29 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiries', '0005_alter_integration_pathway'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('greeters', 'Greeters'), ('followup', 'Follow-Up')], default='followup', max_length=20)),
                ('method', models.CharField(choices=[('call', 'Phone Call'), ('sms', 'SMS'), ('email', 'Email'), ('visit', 'In-Person Visit'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=20)),
                ('outcome', models.CharField(choices=[('reached', 'Reached — spoke with member'), ('no_answer', 'No answer'), ('left_message', 'Left a message'), ('not_available', 'Not available'), ('visited', 'Visit completed'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('contacted_on', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_logs', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_logs', to='enquiries.member')),
            ],
            options={
                'ordering': ['-contacted_on', '-created_at'],
            },
        ),
    ]
