# Generated by Django 4.2.7 on 2026-04-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0006_contactlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='follow_up_round',
            field=models.IntegerField(choices=[(1, 'First Follow-Up'), (2, 'Second Follow-Up')], default=1, help_text='Which follow-up round this is'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('new', 'New Visitor'), ('integrated', 'Integrated Member'), ('inactive', 'Inactive')], default='new', max_length=20),
        ),
    ]
