# Generated by Django 4.2.7 on 2026-04-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0007_followup_follow_up_round_alter_member_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('new', 'New Visitor'), ('integrated', 'Member'), ('inactive', 'Inactive')], default='new', max_length=20),
        ),
    ]
