# Generated by Django 4.2.7 on 2026-04-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0008_alter_member_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='round2_completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='round2_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='round2_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='round2_outcome',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='round2_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('completed', 'Completed'), ('no_response', 'No Response')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='round2_type',
            field=models.CharField(blank=True, choices=[('call', 'Phone Call'), ('email', 'Email'), ('sms', 'SMS'), ('visit', 'Personal Visit'), ('whatsapp', 'WhatsApp')], max_length=20, null=True),
        ),
    ]
