# Generated by Django 4.2.7 on 2026-04-30 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enquiries', '0009_followup_round2_completed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followup',
            name='follow_up_type',
            field=models.CharField(choices=[('call', 'Phone Call'), ('visit', 'Personal Visit')], default='call', max_length=20),
        ),
        migrations.AlterField(
            model_name='followup',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='GreeterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacted_date', models.DateField(blank=True, null=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_greeter_tasks', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='greeter_assignments', to=settings.AUTH_USER_MODEL)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='greeter_assignment', to='enquiries.member')),
            ],
        ),
    ]
