# Generated by Django 4.2.7 on 2026-04-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0010_alter_followup_follow_up_type_alter_followup_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GreeterAssignment',
        ),
    ]
