# Generated by Django 4.2.7 on 2026-04-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0011_delete_greeterassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='is_contacted',
            field=models.BooleanField(default=False),
        ),
    ]
